/**
 * Generates the Material palettes for Zefile's colours.
 *
 * Material 3 Expressive takes an explicit palette of thirteen-odd tones per
 * role; it does not derive them from a seed, despite what its site suggests.
 * The derivation is real colour science in the HCT space, so this uses Google's
 * own implementation rather than approximating it — a palette guessed by eye
 * fails the contrast checks the library runs, and deservedly.
 *
 * The output is committed, so neither this script nor its dependencies are part
 * of installing or building the application — they are fetched on demand:
 *
 *     pnpm run generate:theme
 *
 *   pnpm run generate:theme
 */
import { writeFileSync } from 'node:fs'
// The package publishes ESM whose internal imports omit file extensions, which
// Node refuses to resolve. A bundler does not care, which is why this script is
// run through tsx rather than node directly.
import { Hct, TonalPalette, argbFromHex, hexFromArgb } from '@material/material-color-utilities'

const seeds = {
  primary: '#2F5D50', // pine
  tertiary: '#8E6528', // brass
  error: '#9E3826',
}

/** The tone stops each role needs, taken from what the library asks for. */
const stops = {
  standard: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100],
  neutral: [
    0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 99, 100,
  ],
}

function palette(hue, chroma, tones) {
  const scale = TonalPalette.fromHueAndChroma(hue, chroma)
  return Object.fromEntries(tones.map((tone) => [tone, hexFromArgb(scale.tone(tone))]))
}

const primary = Hct.fromInt(argbFromHex(seeds.primary))
const tertiary = Hct.fromInt(argbFromHex(seeds.tertiary))
const error = Hct.fromInt(argbFromHex(seeds.error))

// Secondary and the neutrals are derived from the primary hue at progressively
// lower chroma, which is how Material builds a scheme that reads as one family
// rather than as a colour placed next to unrelated greys. The chroma values are
// Material's own defaults for a tonal scheme.
const roles = {
  primary: palette(primary.hue, Math.max(48, primary.chroma), stops.standard),
  secondary: palette(primary.hue, 16, stops.standard),
  tertiary: palette(tertiary.hue, Math.max(24, tertiary.chroma), stops.standard),
  neutral: palette(primary.hue, 4, stops.neutral),
  'neutral-variant': palette(primary.hue, 8, stops.standard),
  error: palette(error.hue, Math.max(48, error.chroma), stops.standard),
}

const entries = ["  black: '#000000',", "  white: '#ffffff',"]
for (const [role, tones] of Object.entries(roles)) {
  for (const [tone, hex] of Object.entries(tones)) {
    entries.push(`  '${role}-${tone}': '${hex}',`)
  }
}

const output = `// Code generated by scripts/generate-theme.ts. DO NOT EDIT.
//
// Regenerate with: pnpm run generate:theme
//
// Seeds: primary ${seeds.primary}, tertiary ${seeds.tertiary}, error ${seeds.error}.
// Secondary and the neutrals share the primary hue at lower chroma, so the
// scheme reads as one family rather than a colour beside unrelated greys.

export const palette = {
${entries.join('\n')}
} as const
`

writeFileSync(new URL('../src/theme.generated.ts', import.meta.url), output)
console.log(`wrote ${entries.length} palette entries`)
