// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acl.sql

package sqlcgen

import (
	"context"
	"strings"
)

const deleteACL = `-- name: DeleteACL :exec
DELETE FROM acl WHERE id = ?
`

func (q *Queries) DeleteACL(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteACL, id)
	return err
}

const deleteACLForSubject = `-- name: DeleteACLForSubject :exec
DELETE FROM acl WHERE subject_type = ? AND subject_id = ?
`

type DeleteACLForSubjectParams struct {
	SubjectType string
	SubjectID   int64
}

func (q *Queries) DeleteACLForSubject(ctx context.Context, arg DeleteACLForSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteACLForSubject, arg.SubjectType, arg.SubjectID)
	return err
}

const listACLForGroups = `-- name: ListACLForGroups :many
SELECT id, subject_type, subject_id, path, perms, "recursive", deny, created_at FROM acl
WHERE subject_type = 'group' AND subject_id IN (/*SLICE:group_ids*/?)
`

func (q *Queries) ListACLForGroups(ctx context.Context, groupIds []int64) ([]Acl, error) {
	query := listACLForGroups
	var queryParams []interface{}
	if len(groupIds) > 0 {
		for _, v := range groupIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:group_ids*/?", strings.Repeat(",?", len(groupIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:group_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Acl{}
	for rows.Next() {
		var i Acl
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Path,
			&i.Perms,
			&i.Recursive,
			&i.Deny,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACLForPath = `-- name: ListACLForPath :many
SELECT id, subject_type, subject_id, path, perms, "recursive", deny, created_at FROM acl WHERE path = ? ORDER BY subject_type, subject_id
`

// Backs the permissions screen: everything granted at one exact path.
func (q *Queries) ListACLForPath(ctx context.Context, path string) ([]Acl, error) {
	rows, err := q.db.QueryContext(ctx, listACLForPath, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Acl{}
	for rows.Next() {
		var i Acl
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Path,
			&i.Perms,
			&i.Recursive,
			&i.Deny,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACLForUser = `-- name: ListACLForUser :many
SELECT id, subject_type, subject_id, path, perms, "recursive", deny, created_at FROM acl WHERE subject_type = 'user' AND subject_id = ?
`

func (q *Queries) ListACLForUser(ctx context.Context, subjectID int64) ([]Acl, error) {
	rows, err := q.db.QueryContext(ctx, listACLForUser, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Acl{}
	for rows.Next() {
		var i Acl
		if err := rows.Scan(
			&i.ID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Path,
			&i.Perms,
			&i.Recursive,
			&i.Deny,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT group_id FROM group_members WHERE user_id = ?
`

func (q *Queries) ListGroupsForUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveACLSubtree = `-- name: MoveACLSubtree :exec
UPDATE acl
SET path = ?1 || substr(path, length(?2) + 1)
WHERE path = ?2
   OR substr(path, 1, length(?2) + 1) = ?2 || '/'
`

type MoveACLSubtreeParams struct {
	ToPath   string
	FromPath interface{}
}

// Follows a rename: rewrite every rule at the path or anywhere beneath it, so a
// renamed folder carries its permissions with it instead of leaving them
// stranded on a name that no longer exists. The substr comparison avoids LIKE,
// whose wildcards a path containing '%' or '_' would trip.
func (q *Queries) MoveACLSubtree(ctx context.Context, arg MoveACLSubtreeParams) error {
	_, err := q.db.ExecContext(ctx, moveACLSubtree, arg.ToPath, arg.FromPath)
	return err
}

const upsertACL = `-- name: UpsertACL :one
INSERT INTO acl (subject_type, subject_id, path, perms, recursive, deny, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (subject_type, subject_id, path, deny)
DO UPDATE SET perms = excluded.perms, recursive = excluded.recursive
RETURNING id, subject_type, subject_id, path, perms, "recursive", deny, created_at
`

type UpsertACLParams struct {
	SubjectType string
	SubjectID   int64
	Path        string
	Perms       int64
	Recursive   int64
	Deny        int64
	CreatedAt   int64
}

func (q *Queries) UpsertACL(ctx context.Context, arg UpsertACLParams) (Acl, error) {
	row := q.db.QueryRowContext(ctx, upsertACL,
		arg.SubjectType,
		arg.SubjectID,
		arg.Path,
		arg.Perms,
		arg.Recursive,
		arg.Deny,
		arg.CreatedAt,
	)
	var i Acl
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Path,
		&i.Perms,
		&i.Recursive,
		&i.Deny,
		&i.CreatedAt,
	)
	return i, err
}
