// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, scopes, created_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, name, token_hash, prefix, scopes, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPITokenParams struct {
	UserID    int64
	Name      string
	TokenHash []byte
	Prefix    string
	Scopes    string
	CreatedAt int64
	ExpiresAt sql.NullInt64
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT api_tokens.id, api_tokens.user_id, api_tokens.name, api_tokens.token_hash, api_tokens.prefix, api_tokens.scopes, api_tokens.created_at, api_tokens.last_used_at, api_tokens.expires_at, api_tokens.revoked_at, users.id, users.username, users.email, users.password_hash, users.is_admin, users.totp_secret, users.disabled, users.created_at, users.updated_at
FROM api_tokens
JOIN users ON users.id = api_tokens.user_id
WHERE api_tokens.token_hash = ?
  AND api_tokens.revoked_at IS NULL
  AND (api_tokens.expires_at IS NULL OR api_tokens.expires_at > ?)
  AND users.disabled = 0
`

type GetAPITokenByHashParams struct {
	TokenHash []byte
	ExpiresAt sql.NullInt64
}

type GetAPITokenByHashRow struct {
	ApiToken ApiToken
	User     User
}

// The lookup performed on every request that arrives with a zefile_live_ token.
// Expiry and revocation are filtered here, alongside the account being enabled,
// so a caller cannot present a token whose owner has been disabled. A NULL
// expires_at means the token never expires.
func (q *Queries) GetAPITokenByHash(ctx context.Context, arg GetAPITokenByHashParams) (GetAPITokenByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, arg.TokenHash, arg.ExpiresAt)
	var i GetAPITokenByHashRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.UserID,
		&i.ApiToken.Name,
		&i.ApiToken.TokenHash,
		&i.ApiToken.Prefix,
		&i.ApiToken.Scopes,
		&i.ApiToken.CreatedAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.RevokedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.TotpSecret,
		&i.User.Disabled,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listAPITokensForUser = `-- name: ListAPITokensForUser :many
SELECT id, user_id, name, token_hash, prefix, scopes, created_at, last_used_at, expires_at, revoked_at FROM api_tokens
WHERE user_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

// The management list. Revoked tokens are dropped so the screen shows only what
// is still live; the plaintext is never held, so only the prefix is shown.
func (q *Queries) ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, listAPITokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPITokenForUser = `-- name: RevokeAPITokenForUser :execrows
UPDATE api_tokens SET revoked_at = ?
WHERE id = ? AND user_id = ? AND revoked_at IS NULL
`

type RevokeAPITokenForUserParams struct {
	RevokedAt sql.NullInt64
	ID        int64
	UserID    int64
}

// Scoped to the owner so one account cannot revoke another's token by guessing
// an id. execrows lets the handler answer 404 when nothing matched.
func (q *Queries) RevokeAPITokenForUser(ctx context.Context, arg RevokeAPITokenForUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAPITokenForUser, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = ? WHERE id = ?
`

type TouchAPITokenParams struct {
	LastUsedAt sql.NullInt64
	ID         int64
}

// Records use for the "last used" column. Best-effort, like session touch: a
// lost timestamp must never fail an otherwise-valid request.
func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.ExecContext(ctx, touchAPIToken, arg.LastUsedAt, arg.ID)
	return err
}
