// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAuditEntriesBefore = `-- name: DeleteAuditEntriesBefore :execrows
DELETE FROM audit_log WHERE at < ?
`

// Retention purge: drop entries older than a cutoff. The audit log records IP
// addresses, so keeping it bounded is a privacy measure, not only housekeeping.
func (q *Queries) DeleteAuditEntriesBefore(ctx context.Context, at int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditEntriesBefore, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (at, actor_id, actor_ip, action, target, details)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertAuditEntryParams struct {
	At      int64
	ActorID sql.NullInt64
	ActorIp string
	Action  string
	Target  string
	Details string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditEntry,
		arg.At,
		arg.ActorID,
		arg.ActorIp,
		arg.Action,
		arg.Target,
		arg.Details,
	)
	return err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT a.id, a.at, a.actor_id, a.actor_ip, a.action, a.target, a.details, u.username AS actor_username
FROM audit_log a
LEFT JOIN users u ON u.id = a.actor_id
WHERE a.id < ?
ORDER BY a.id DESC
LIMIT ?
`

type ListAuditEntriesParams struct {
	ID    int64
	Limit int64
}

type ListAuditEntriesRow struct {
	ID            int64
	At            int64
	ActorID       sql.NullInt64
	ActorIp       string
	Action        string
	Target        string
	Details       string
	ActorUsername sql.NullString
}

// Newest first, keyset-paginated by id (strictly decreasing). Pass a large id
// for the first page. The actor's name is joined in; it is null when the account
// was since deleted, which the entry still records by id and ip.
func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEntries, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEntriesRow{}
	for rows.Next() {
		var i ListAuditEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorID,
			&i.ActorIp,
			&i.Action,
			&i.Target,
			&i.Details,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
