// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checksums.sql

package sqlcgen

import (
	"context"
)

const getChecksum = `-- name: GetChecksum :one
SELECT path, algo, hash, size, modified_at, computed_at FROM checksums WHERE path = ?
`

func (q *Queries) GetChecksum(ctx context.Context, path string) (Checksum, error) {
	row := q.db.QueryRowContext(ctx, getChecksum, path)
	var i Checksum
	err := row.Scan(
		&i.Path,
		&i.Algo,
		&i.Hash,
		&i.Size,
		&i.ModifiedAt,
		&i.ComputedAt,
	)
	return i, err
}

const upsertChecksum = `-- name: UpsertChecksum :exec
INSERT INTO checksums (path, algo, hash, size, modified_at, computed_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    algo = excluded.algo, hash = excluded.hash, size = excluded.size,
    modified_at = excluded.modified_at, computed_at = excluded.computed_at
`

type UpsertChecksumParams struct {
	Path       string
	Algo       string
	Hash       string
	Size       int64
	ModifiedAt int64
	ComputedAt int64
}

func (q *Queries) UpsertChecksum(ctx context.Context, arg UpsertChecksumParams) error {
	_, err := q.db.ExecContext(ctx, upsertChecksum,
		arg.Path,
		arg.Algo,
		arg.Hash,
		arg.Size,
		arg.ModifiedAt,
		arg.ComputedAt,
	)
	return err
}
