// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_owners.sql

package sqlcgen

import (
	"context"
	"strings"
)

const deleteFileOwner = `-- name: DeleteFileOwner :exec
DELETE FROM file_owners WHERE path = ?
`

func (q *Queries) DeleteFileOwner(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFileOwner, path)
	return err
}

const getFileOwner = `-- name: GetFileOwner :one
SELECT path, owner_id, created_at FROM file_owners WHERE path = ?
`

func (q *Queries) GetFileOwner(ctx context.Context, path string) (FileOwner, error) {
	row := q.db.QueryRowContext(ctx, getFileOwner, path)
	var i FileOwner
	err := row.Scan(&i.Path, &i.OwnerID, &i.CreatedAt)
	return i, err
}

const getFileOwnersForPaths = `-- name: GetFileOwnersForPaths :many
SELECT path, owner_id, created_at FROM file_owners WHERE path IN (/*SLICE:paths*/?)
`

// Batched so that listing a directory costs one query rather than one per entry.
func (q *Queries) GetFileOwnersForPaths(ctx context.Context, paths []string) ([]FileOwner, error) {
	query := getFileOwnersForPaths
	var queryParams []interface{}
	if len(paths) > 0 {
		for _, v := range paths {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:paths*/?", strings.Repeat(",?", len(paths))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:paths*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileOwner{}
	for rows.Next() {
		var i FileOwner
		if err := rows.Scan(&i.Path, &i.OwnerID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveFileOwner = `-- name: MoveFileOwner :exec
UPDATE file_owners SET path = ? WHERE path = ?
`

type MoveFileOwnerParams struct {
	Path   string
	Path_2 string
}

func (q *Queries) MoveFileOwner(ctx context.Context, arg MoveFileOwnerParams) error {
	_, err := q.db.ExecContext(ctx, moveFileOwner, arg.Path, arg.Path_2)
	return err
}

const setFileOwner = `-- name: SetFileOwner :exec
INSERT INTO file_owners (path, owner_id, created_at) VALUES (?, ?, ?)
ON CONFLICT (path) DO UPDATE SET owner_id = excluded.owner_id
`

type SetFileOwnerParams struct {
	Path      string
	OwnerID   int64
	CreatedAt int64
}

func (q *Queries) SetFileOwner(ctx context.Context, arg SetFileOwnerParams) error {
	_, err := q.db.ExecContext(ctx, setFileOwner, arg.Path, arg.OwnerID, arg.CreatedAt)
	return err
}
