// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcgen

import (
	"context"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, created_at) VALUES (?, ?) RETURNING id, name, created_at
`

type CreateGroupParams struct {
	Name      string
	CreatedAt int64
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.CreatedAt)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const groupExists = `-- name: GroupExists :one
SELECT count(*) FROM groups WHERE id = ?
`

func (q *Queries) GroupExists(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, groupExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listGroupMemberIDs = `-- name: ListGroupMemberIDs :many
SELECT user_id FROM group_members WHERE group_id = ?
`

func (q *Queries) ListGroupMemberIDs(ctx context.Context, groupID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMemberIDs, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.created_at, COUNT(gm.user_id) AS member_count
FROM groups g
LEFT JOIN group_members gm ON gm.group_id = g.id
GROUP BY g.id
ORDER BY g.name
`

type ListGroupsRow struct {
	ID          int64
	Name        string
	CreatedAt   int64
	MemberCount int64
}

// Groups with how many members each holds, for the management screen.
func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = ? AND user_id = ?
`

type RemoveGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}
