// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (token_hash, email, inviter_id, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token_hash, email, inviter_id, created_at, expires_at, used_at
`

type CreateInvitationParams struct {
	TokenHash []byte
	Email     sql.NullString
	InviterID sql.NullInt64
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.TokenHash,
		arg.Email,
		arg.InviterID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteInvitationByID = `-- name: DeleteInvitationByID :execrows
DELETE FROM invitations WHERE id = ? AND used_at IS NULL AND inviter_id IS NOT NULL
`

// Only an unused, real invitation can be revoked; a used one has already become
// an account, and a setup token is not an admin's to cancel.
func (q *Queries) DeleteInvitationByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvitationByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUnusedInvitations = `-- name: DeleteUnusedInvitations :exec
DELETE FROM invitations WHERE used_at IS NULL AND inviter_id IS NULL
`

func (q *Queries) DeleteUnusedInvitations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedInvitations)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, token_hash, email, inviter_id, created_at, expires_at, used_at FROM invitations
WHERE token_hash = ? AND used_at IS NULL AND expires_at > ?
`

type GetInvitationByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt int64
}

// Single use and expiry are filtered here, so a caller cannot accidentally
// accept an invitation twice.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, arg GetInvitationByTokenHashParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, token_hash, email, inviter_id, created_at, expires_at, used_at FROM invitations
WHERE used_at IS NULL AND inviter_id IS NOT NULL AND expires_at > ?
ORDER BY created_at DESC
`

// Real invitations (those with an inviter) that are still open, newest first.
// Setup tokens have no inviter and are excluded.
func (q *Queries) ListPendingInvitations(ctx context.Context, expiresAt int64) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listPendingInvitations, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.Email,
			&i.InviterID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE invitations SET used_at = ? WHERE id = ? AND used_at IS NULL
`

type MarkInvitationUsedParams struct {
	UsedAt sql.NullInt64
	ID     int64
}

func (q *Queries) MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInvitationUsed, arg.UsedAt, arg.ID)
	return err
}
