// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (token_hash, email, inviter_id, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, token_hash, email, inviter_id, created_at, expires_at, used_at
`

type CreateInvitationParams struct {
	TokenHash []byte
	Email     sql.NullString
	InviterID sql.NullInt64
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, createInvitation,
		arg.TokenHash,
		arg.Email,
		arg.InviterID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteUnusedInvitations = `-- name: DeleteUnusedInvitations :exec
DELETE FROM invitations WHERE used_at IS NULL AND inviter_id IS NULL
`

func (q *Queries) DeleteUnusedInvitations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUnusedInvitations)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, token_hash, email, inviter_id, created_at, expires_at, used_at FROM invitations
WHERE token_hash = ? AND used_at IS NULL AND expires_at > ?
`

type GetInvitationByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt int64
}

// Single use and expiry are filtered here, so a caller cannot accidentally
// accept an invitation twice.
func (q *Queries) GetInvitationByTokenHash(ctx context.Context, arg GetInvitationByTokenHashParams) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Email,
		&i.InviterID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markInvitationUsed = `-- name: MarkInvitationUsed :exec
UPDATE invitations SET used_at = ? WHERE id = ? AND used_at IS NULL
`

type MarkInvitationUsedParams struct {
	UsedAt sql.NullInt64
	ID     int64
}

func (q *Queries) MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error {
	_, err := q.db.ExecContext(ctx, markInvitationUsed, arg.UsedAt, arg.ID)
	return err
}
