// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const claimNextJob = `-- name: ClaimNextJob :one
UPDATE jobs
SET status = 'running', started_at = ?
WHERE id = (SELECT id FROM jobs WHERE status = 'pending' ORDER BY created_at, id LIMIT 1)
RETURNING id, type, payload, status, progress, error, created_at, started_at, finished_at
`

// Atomically take the oldest pending job and mark it running. The single writer
// connection serialises this, so two workers could not claim the same row.
func (q *Queries) ClaimNextJob(ctx context.Context, startedAt sql.NullInt64) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimNextJob, startedAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, payload, status, created_at)
VALUES (?, ?, 'pending', ?)
RETURNING id, type, payload, status, progress, error, created_at, started_at, finished_at
`

type CreateJobParams struct {
	Type      string
	Payload   string
	CreatedAt int64
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob, arg.Type, arg.Payload, arg.CreatedAt)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishJob = `-- name: FinishJob :exec
UPDATE jobs SET status = ?, progress = ?, error = ?, finished_at = ? WHERE id = ?
`

type FinishJobParams struct {
	Status     string
	Progress   float64
	Error      sql.NullString
	FinishedAt sql.NullInt64
	ID         int64
}

func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.FinishedAt,
		arg.ID,
	)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, type, payload, status, progress, error, created_at, started_at, finished_at FROM jobs WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listRecentJobs = `-- name: ListRecentJobs :many
SELECT id, type, payload, status, progress, error, created_at, started_at, finished_at FROM jobs ORDER BY created_at DESC, id DESC LIMIT ?
`

func (q *Queries) ListRecentJobs(ctx context.Context, limit int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listRecentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueRunningJobs = `-- name: RequeueRunningJobs :exec
UPDATE jobs SET status = 'pending', started_at = NULL WHERE status = 'running'
`

// A job left 'running' by a crash is reset so the worker picks it up again on
// the next start; its own idempotent construction makes the retry safe.
func (q *Queries) RequeueRunningJobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, requeueRunningJobs)
	return err
}

const updateJobProgress = `-- name: UpdateJobProgress :exec
UPDATE jobs SET progress = ? WHERE id = ?
`

type UpdateJobProgressParams struct {
	Progress float64
	ID       int64
}

func (q *Queries) UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateJobProgress, arg.Progress, arg.ID)
	return err
}
