// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Acl struct {
	ID          int64
	SubjectType string
	SubjectID   int64
	Path        string
	Perms       int64
	Recursive   int64
	Deny        int64
	CreatedAt   int64
}

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  []byte
	Prefix     string
	Scopes     string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	ExpiresAt  sql.NullInt64
	RevokedAt  sql.NullInt64
}

type AuditLog struct {
	ID      int64
	At      int64
	ActorID sql.NullInt64
	ActorIp string
	Action  string
	Target  string
	Details string
}

type FileIndex struct {
	Path string
	Name string
}

type FileOwner struct {
	Path      string
	OwnerID   int64
	CreatedAt int64
}

type Group struct {
	ID        int64
	Name      string
	CreatedAt int64
}

type GroupMember struct {
	GroupID int64
	UserID  int64
}

type Invitation struct {
	ID        int64
	TokenHash []byte
	Email     sql.NullString
	InviterID sql.NullInt64
	CreatedAt int64
	ExpiresAt int64
	UsedAt    sql.NullInt64
}

type Job struct {
	ID         int64
	Type       string
	Payload    string
	Status     string
	Progress   float64
	Error      sql.NullString
	CreatedAt  int64
	StartedAt  sql.NullInt64
	FinishedAt sql.NullInt64
}

type Session struct {
	ID         int64
	UserID     int64
	TokenHash  []byte
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	UserAgent  string
	Ip         string
	RevokedAt  sql.NullInt64
}

type Share struct {
	ID            int64
	TokenHash     []byte
	OwnerID       int64
	Path          string
	Perms         int64
	PasswordHash  sql.NullString
	MaxDownloads  sql.NullInt64
	DownloadCount int64
	CreatedAt     int64
	ExpiresAt     sql.NullInt64
	RevokedAt     sql.NullInt64
}

type ShareAccessLog struct {
	ID        int64
	ShareID   int64
	At        int64
	Ip        string
	UserAgent string
	BytesSent int64
}

type Trash struct {
	ID           int64
	TrashName    string
	OriginalPath string
	DeletedBy    sql.NullInt64
	DeletedAt    int64
	IsDir        int64
}

type Upload struct {
	ID         int64
	Token      string
	UserID     int64
	TargetPath string
	Size       int64
	Received   int64
	Checksum   sql.NullString
	CreatedAt  int64
	ExpiresAt  int64
}

type User struct {
	ID           int64
	Username     string
	Email        sql.NullString
	PasswordHash string
	IsAdmin      int64
	TotpSecret   sql.NullString
	Disabled     int64
	CreatedAt    int64
	UpdatedAt    int64
}
