// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	// Atomically take the oldest pending job and mark it running. The single writer
	// connection serialises this, so two workers could not claim the same row.
	ClaimNextJob(ctx context.Context, startedAt sql.NullInt64) (Job, error)
	CountUnusedRecoveryCodesForUser(ctx context.Context, userID int64) (int64, error)
	// Backs first-run detection: an instance with no account shows the setup link
	// rather than a sign-in form.
	CountUsers(ctx context.Context) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// max_downloads stays in the table but is left NULL: the download-limit feature
	// was removed, and the column is kept only to avoid a migration.
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateTrash(ctx context.Context, arg CreateTrashParams) (Trash, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteACL(ctx context.Context, id int64) error
	DeleteACLForSubject(ctx context.Context, arg DeleteACLForSubjectParams) error
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) error
	DeleteFileOwner(ctx context.Context, path string) error
	DeleteGroup(ctx context.Context, id int64) (int64, error)
	// Only an unused, real invitation can be revoked; a used one has already become
	// an account, and a setup token is not an admin's to cancel.
	DeleteInvitationByID(ctx context.Context, id int64) (int64, error)
	// Regenerating replaces the whole set, so the old codes are cleared first.
	DeleteRecoveryCodesForUser(ctx context.Context, userID int64) error
	DeleteTrash(ctx context.Context, id int64) error
	DeleteUnusedInvitations(ctx context.Context) error
	DeleteUpload(ctx context.Context, id int64) error
	// Sessions and file ownership cascade with the row; ACL rules are keyed by a
	// subject type as well as an id, so they carry no foreign key and are cleared
	// separately by the caller.
	DeleteUser(ctx context.Context, id int64) error
	FinishJob(ctx context.Context, arg FinishJobParams) error
	// The lookup performed on every request that arrives with a zefile_live_ token.
	// Expiry and revocation are filtered here, alongside the account being enabled,
	// so a caller cannot present a token whose owner has been disabled. A NULL
	// expires_at means the token never expires.
	GetAPITokenByHash(ctx context.Context, arg GetAPITokenByHashParams) (GetAPITokenByHashRow, error)
	GetFileOwner(ctx context.Context, path string) (FileOwner, error)
	// Batched so that listing a directory costs one query rather than one per entry.
	GetFileOwnersForPaths(ctx context.Context, paths []string) ([]FileOwner, error)
	// Single use and expiry are filtered here, so a caller cannot accidentally
	// accept an invitation twice.
	GetInvitationByTokenHash(ctx context.Context, arg GetInvitationByTokenHashParams) (Invitation, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	// The lookup performed on every authenticated request. Expiry and revocation
	// are filtered here rather than in Go: a caller that forgets the check must not
	// be able to resurrect a dead session.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error)
	// The status (expired, revoked, exhausted) is decided in Go so the public
	// endpoint can tell a holder why a link stopped working; the row is fetched
	// whatever its state.
	GetShareByHash(ctx context.Context, tokenHash []byte) (Share, error)
	GetTrash(ctx context.Context, id int64) (Trash, error)
	// Expiry is filtered here so an abandoned session cannot be revived days later
	// by a client that kept its token.
	GetUpload(ctx context.Context, arg GetUploadParams) (Upload, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GroupExists(ctx context.Context, id int64) (int64, error)
	IncrementShareDownloads(ctx context.Context, id int64) error
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error
	ListACLForGroups(ctx context.Context, groupIds []int64) ([]Acl, error)
	// Backs the permissions screen: everything granted at one exact path.
	ListACLForPath(ctx context.Context, path string) ([]Acl, error)
	ListACLForUser(ctx context.Context, subjectID int64) ([]Acl, error)
	// The management list. Revoked tokens are dropped so the screen shows only what
	// is still live; the plaintext is never held, so only the prefix is shown.
	ListAPITokensForUser(ctx context.Context, userID int64) ([]ApiToken, error)
	// Newest first, keyset-paginated by id (strictly decreasing). Pass a large id
	// for the first page. The actor's name is joined in; it is null when the account
	// was since deleted, which the entry still records by id and ip.
	ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error)
	ListExpiredUploads(ctx context.Context, expiresAt int64) ([]Upload, error)
	ListGroupMemberIDs(ctx context.Context, groupID int64) ([]int64, error)
	// Groups with how many members each holds, for the management screen.
	ListGroups(ctx context.Context) ([]ListGroupsRow, error)
	ListGroupsForUser(ctx context.Context, userID int64) ([]int64, error)
	// Real invitations (those with an inviter) that are still open, newest first.
	// Setup tokens have no inviter and are excluded.
	ListPendingInvitations(ctx context.Context, expiresAt int64) ([]Invitation, error)
	ListRecentJobs(ctx context.Context, limit int64) ([]Job, error)
	ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error)
	ListSharesByOwner(ctx context.Context, ownerID int64) ([]Share, error)
	// Most recently deleted first: that is the order someone reaches for the trash
	// to undo a mistake they just made.
	ListTrash(ctx context.Context) ([]Trash, error)
	// A reset tries the presented code against each unused code for the account.
	ListUnusedRecoveryCodesForUser(ctx context.Context, userID int64) ([]ListUnusedRecoveryCodesForUserRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	LogShareAccess(ctx context.Context, arg LogShareAccessParams) error
	MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error
	// Scoped to an unused code so the same code can never be spent twice, even in a
	// race: execrows lets the caller confirm exactly one row changed.
	MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) (int64, error)
	// Follows a rename: rewrite every rule at the path or anywhere beneath it, so a
	// renamed folder carries its permissions with it instead of leaving them
	// stranded on a name that no longer exists. The substr comparison avoids LIKE,
	// whose wildcards a path containing '%' or '_' would trip.
	MoveACLSubtree(ctx context.Context, arg MoveACLSubtreeParams) error
	// Follows a rename across a whole subtree, so a moved folder keeps ownership of
	// everything inside it, not only its own row.
	MoveFileOwner(ctx context.Context, arg MoveFileOwnerParams) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// A job left 'running' by a crash is reset so the worker picks it up again on
	// the next start; its own idempotent construction makes the retry safe.
	RequeueRunningJobs(ctx context.Context) error
	// Scoped to the owner so one account cannot revoke another's token by guessing
	// an id. execrows lets the handler answer 404 when nothing matched.
	RevokeAPITokenForUser(ctx context.Context, arg RevokeAPITokenForUserParams) (int64, error)
	RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error
	// Signs the account out everywhere but the session making the request.
	RevokeOtherSessionsForUser(ctx context.Context, arg RevokeOtherSessionsForUserParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	// Scoped to the owner so one account cannot end another's session by guessing
	// an id.
	RevokeSessionForUser(ctx context.Context, arg RevokeSessionForUserParams) (int64, error)
	RevokeShare(ctx context.Context, arg RevokeShareParams) (int64, error)
	SetFileOwner(ctx context.Context, arg SetFileOwnerParams) error
	// Sets or clears (NULL) the TOTP secret. A non-NULL secret means two-factor
	// authentication is enabled for the account.
	SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error
	// Records use for the "last used" column. Best-effort, like session touch: a
	// lost timestamp must never fail an otherwise-valid request.
	TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error
	UpdateUploadOffset(ctx context.Context, arg UpdateUploadOffsetParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertACL(ctx context.Context, arg UpsertACLParams) (Acl, error)
}

var _ Querier = (*Queries)(nil)
