// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Atomically take the oldest pending job and mark it running. The single writer
	// connection serialises this, so two workers could not claim the same row.
	ClaimNextJob(ctx context.Context, startedAt sql.NullInt64) (Job, error)
	// Backs first-run detection: an instance with no account shows the setup link
	// rather than a sign-in form.
	CountUsers(ctx context.Context) (int64, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// max_downloads stays in the table but is left NULL: the download-limit feature
	// was removed, and the column is kept only to avoid a migration.
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	CreateTrash(ctx context.Context, arg CreateTrashParams) (Trash, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteACL(ctx context.Context, id int64) error
	DeleteACLForSubject(ctx context.Context, arg DeleteACLForSubjectParams) error
	DeleteExpiredSessions(ctx context.Context, expiresAt int64) error
	DeleteFileOwner(ctx context.Context, path string) error
	// Only an unused, real invitation can be revoked; a used one has already become
	// an account, and a setup token is not an admin's to cancel.
	DeleteInvitationByID(ctx context.Context, id int64) (int64, error)
	DeleteTrash(ctx context.Context, id int64) error
	DeleteUnusedInvitations(ctx context.Context) error
	DeleteUpload(ctx context.Context, id int64) error
	FinishJob(ctx context.Context, arg FinishJobParams) error
	GetFileOwner(ctx context.Context, path string) (FileOwner, error)
	// Batched so that listing a directory costs one query rather than one per entry.
	GetFileOwnersForPaths(ctx context.Context, paths []string) ([]FileOwner, error)
	// Single use and expiry are filtered here, so a caller cannot accidentally
	// accept an invitation twice.
	GetInvitationByTokenHash(ctx context.Context, arg GetInvitationByTokenHashParams) (Invitation, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	// The lookup performed on every authenticated request. Expiry and revocation
	// are filtered here rather than in Go: a caller that forgets the check must not
	// be able to resurrect a dead session.
	GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error)
	// The status (expired, revoked, exhausted) is decided in Go so the public
	// endpoint can tell a holder why a link stopped working; the row is fetched
	// whatever its state.
	GetShareByHash(ctx context.Context, tokenHash []byte) (Share, error)
	GetTrash(ctx context.Context, id int64) (Trash, error)
	// Expiry is filtered here so an abandoned session cannot be revived days later
	// by a client that kept its token.
	GetUpload(ctx context.Context, arg GetUploadParams) (Upload, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IncrementShareDownloads(ctx context.Context, id int64) error
	ListACLForGroups(ctx context.Context, groupIds []int64) ([]Acl, error)
	// Backs the permissions screen: everything granted at one exact path.
	ListACLForPath(ctx context.Context, path string) ([]Acl, error)
	ListACLForUser(ctx context.Context, subjectID int64) ([]Acl, error)
	ListExpiredUploads(ctx context.Context, expiresAt int64) ([]Upload, error)
	ListGroupsForUser(ctx context.Context, userID int64) ([]int64, error)
	// Real invitations (those with an inviter) that are still open, newest first.
	// Setup tokens have no inviter and are excluded.
	ListPendingInvitations(ctx context.Context, expiresAt int64) ([]Invitation, error)
	ListRecentJobs(ctx context.Context, limit int64) ([]Job, error)
	ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error)
	ListSharesByOwner(ctx context.Context, ownerID int64) ([]Share, error)
	// Most recently deleted first: that is the order someone reaches for the trash
	// to undo a mistake they just made.
	ListTrash(ctx context.Context) ([]Trash, error)
	LogShareAccess(ctx context.Context, arg LogShareAccessParams) error
	MarkInvitationUsed(ctx context.Context, arg MarkInvitationUsedParams) error
	MoveFileOwner(ctx context.Context, arg MoveFileOwnerParams) error
	// A job left 'running' by a crash is reset so the worker picks it up again on
	// the next start; its own idempotent construction makes the retry safe.
	RequeueRunningJobs(ctx context.Context) error
	RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeShare(ctx context.Context, arg RevokeShareParams) (int64, error)
	SetFileOwner(ctx context.Context, arg SetFileOwnerParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateJobProgress(ctx context.Context, arg UpdateJobProgressParams) error
	UpdateUploadOffset(ctx context.Context, arg UpdateUploadOffsetParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertACL(ctx context.Context, arg UpsertACLParams) (Acl, error)
}

var _ Querier = (*Queries)(nil)
