// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countUnusedRecoveryCodesForUser = `-- name: CountUnusedRecoveryCodesForUser :one
SELECT count(*) FROM recovery_codes WHERE user_id = ? AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodesForUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash, created_at) VALUES (?, ?, ?)
`

type CreateRecoveryCodeParams struct {
	UserID    int64
	CodeHash  string
	CreatedAt int64
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRecoveryCode, arg.UserID, arg.CodeHash, arg.CreatedAt)
	return err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :exec
DELETE FROM recovery_codes WHERE user_id = ?
`

// Regenerating replaces the whole set, so the old codes are cleared first.
func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodesForUser, userID)
	return err
}

const listUnusedRecoveryCodesForUser = `-- name: ListUnusedRecoveryCodesForUser :many
SELECT id, code_hash FROM recovery_codes
WHERE user_id = ? AND used_at IS NULL
`

type ListUnusedRecoveryCodesForUserRow struct {
	ID       int64
	CodeHash string
}

// A reset tries the presented code against each unused code for the account.
func (q *Queries) ListUnusedRecoveryCodesForUser(ctx context.Context, userID int64) ([]ListUnusedRecoveryCodesForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnusedRecoveryCodesForUserRow{}
	for rows.Next() {
		var i ListUnusedRecoveryCodesForUserRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :execrows
UPDATE recovery_codes SET used_at = ? WHERE id = ? AND used_at IS NULL
`

type MarkRecoveryCodeUsedParams struct {
	UsedAt sql.NullInt64
	ID     int64
}

// Scoped to an unused code so the same code can never be spent twice, even in a
// race: execrows lets the caller confirm exactly one row changed.
func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, arg.UsedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
