// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, created_at, last_seen_at, expires_at, user_agent, ip)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, token_hash, created_at, last_seen_at, expires_at, user_agent, ip, revoked_at
`

type CreateSessionParams struct {
	UserID     int64
	TokenHash  []byte
	CreatedAt  int64
	LastSeenAt int64
	ExpiresAt  int64
	UserAgent  string
	Ip         string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserAgent,
		&i.Ip,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT sessions.id, sessions.user_id, sessions.token_hash, sessions.created_at, sessions.last_seen_at, sessions.expires_at, sessions.user_agent, sessions.ip, sessions.revoked_at, users.id, users.username, users.email, users.password_hash, users.is_admin, users.totp_secret, users.disabled, users.created_at, users.updated_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = ?
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > ?
  AND users.disabled = 0
`

type GetSessionByTokenHashParams struct {
	TokenHash []byte
	ExpiresAt int64
}

type GetSessionByTokenHashRow struct {
	Session Session
	User    User
}

// The lookup performed on every authenticated request. Expiry and revocation
// are filtered here rather than in Go: a caller that forgets the check must not
// be able to resurrect a dead session.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, arg GetSessionByTokenHashParams) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.TokenHash,
		&i.Session.CreatedAt,
		&i.Session.LastSeenAt,
		&i.Session.ExpiresAt,
		&i.Session.UserAgent,
		&i.Session.Ip,
		&i.Session.RevokedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.TotpSecret,
		&i.User.Disabled,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, token_hash, created_at, last_seen_at, expires_at, user_agent, ip, revoked_at FROM sessions
WHERE user_id = ? AND revoked_at IS NULL AND expires_at > ?
ORDER BY last_seen_at DESC
`

type ListSessionsForUserParams struct {
	UserID    int64
	ExpiresAt int64
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForUser, arg.UserID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.UserAgent,
			&i.Ip,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeAllSessionsForUserParams struct {
	RevokedAt sql.NullInt64
	UserID    int64
}

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsForUser, arg.RevokedAt, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = ? WHERE id = ? AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	RevokedAt sql.NullInt64
	ID        int64
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.RevokedAt, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt int64
	ID         int64
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ID)
	return err
}
