// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createShare = `-- name: CreateShare :one
INSERT INTO shares (
    token_hash, owner_id, path, perms, password_hash,
    download_count, created_at, expires_at, revoked_at
)
VALUES (?, ?, ?, ?, ?, 0, ?, ?, NULL)
RETURNING id, token_hash, owner_id, path, perms, password_hash, max_downloads, download_count, created_at, expires_at, revoked_at
`

type CreateShareParams struct {
	TokenHash    []byte
	OwnerID      int64
	Path         string
	Perms        int64
	PasswordHash sql.NullString
	CreatedAt    int64
	ExpiresAt    sql.NullInt64
}

// max_downloads stays in the table but is left NULL: the download-limit feature
// was removed, and the column is kept only to avoid a migration.
func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRowContext(ctx, createShare,
		arg.TokenHash,
		arg.OwnerID,
		arg.Path,
		arg.Perms,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.OwnerID,
		&i.Path,
		&i.Perms,
		&i.PasswordHash,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareByHash = `-- name: GetShareByHash :one
SELECT id, token_hash, owner_id, path, perms, password_hash, max_downloads, download_count, created_at, expires_at, revoked_at FROM shares WHERE token_hash = ?
`

// The status (expired, revoked, exhausted) is decided in Go so the public
// endpoint can tell a holder why a link stopped working; the row is fetched
// whatever its state.
func (q *Queries) GetShareByHash(ctx context.Context, tokenHash []byte) (Share, error) {
	row := q.db.QueryRowContext(ctx, getShareByHash, tokenHash)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.OwnerID,
		&i.Path,
		&i.Perms,
		&i.PasswordHash,
		&i.MaxDownloads,
		&i.DownloadCount,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementShareDownloads = `-- name: IncrementShareDownloads :exec
UPDATE shares SET download_count = download_count + 1 WHERE id = ?
`

func (q *Queries) IncrementShareDownloads(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementShareDownloads, id)
	return err
}

const listSharesByOwner = `-- name: ListSharesByOwner :many
SELECT id, token_hash, owner_id, path, perms, password_hash, max_downloads, download_count, created_at, expires_at, revoked_at FROM shares
WHERE owner_id = ? AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSharesByOwner(ctx context.Context, ownerID int64) ([]Share, error) {
	rows, err := q.db.QueryContext(ctx, listSharesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.OwnerID,
			&i.Path,
			&i.Perms,
			&i.PasswordHash,
			&i.MaxDownloads,
			&i.DownloadCount,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logShareAccess = `-- name: LogShareAccess :exec
INSERT INTO share_access_log (share_id, at, ip, user_agent, bytes_sent)
VALUES (?, ?, ?, ?, ?)
`

type LogShareAccessParams struct {
	ShareID   int64
	At        int64
	Ip        string
	UserAgent string
	BytesSent int64
}

func (q *Queries) LogShareAccess(ctx context.Context, arg LogShareAccessParams) error {
	_, err := q.db.ExecContext(ctx, logShareAccess,
		arg.ShareID,
		arg.At,
		arg.Ip,
		arg.UserAgent,
		arg.BytesSent,
	)
	return err
}

const revokeShare = `-- name: RevokeShare :execrows
UPDATE shares
SET revoked_at = ?
WHERE id = ? AND owner_id = ? AND revoked_at IS NULL
`

type RevokeShareParams struct {
	RevokedAt sql.NullInt64
	ID        int64
	OwnerID   int64
}

func (q *Queries) RevokeShare(ctx context.Context, arg RevokeShareParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeShare, arg.RevokedAt, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
