// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trash.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createTrash = `-- name: CreateTrash :one
INSERT INTO trash (trash_name, original_path, deleted_by, deleted_at, is_dir)
VALUES (?, ?, ?, ?, ?)
RETURNING id, trash_name, original_path, deleted_by, deleted_at, is_dir
`

type CreateTrashParams struct {
	TrashName    string
	OriginalPath string
	DeletedBy    sql.NullInt64
	DeletedAt    int64
	IsDir        int64
}

func (q *Queries) CreateTrash(ctx context.Context, arg CreateTrashParams) (Trash, error) {
	row := q.db.QueryRowContext(ctx, createTrash,
		arg.TrashName,
		arg.OriginalPath,
		arg.DeletedBy,
		arg.DeletedAt,
		arg.IsDir,
	)
	var i Trash
	err := row.Scan(
		&i.ID,
		&i.TrashName,
		&i.OriginalPath,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.IsDir,
	)
	return i, err
}

const deleteTrash = `-- name: DeleteTrash :exec
DELETE FROM trash WHERE id = ?
`

func (q *Queries) DeleteTrash(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrash, id)
	return err
}

const getTrash = `-- name: GetTrash :one
SELECT id, trash_name, original_path, deleted_by, deleted_at, is_dir FROM trash WHERE id = ?
`

func (q *Queries) GetTrash(ctx context.Context, id int64) (Trash, error) {
	row := q.db.QueryRowContext(ctx, getTrash, id)
	var i Trash
	err := row.Scan(
		&i.ID,
		&i.TrashName,
		&i.OriginalPath,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.IsDir,
	)
	return i, err
}

const listTrash = `-- name: ListTrash :many
SELECT id, trash_name, original_path, deleted_by, deleted_at, is_dir FROM trash ORDER BY deleted_at DESC
`

// Most recently deleted first: that is the order someone reaches for the trash
// to undo a mistake they just made.
func (q *Queries) ListTrash(ctx context.Context) ([]Trash, error) {
	rows, err := q.db.QueryContext(ctx, listTrash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trash{}
	for rows.Next() {
		var i Trash
		if err := rows.Scan(
			&i.ID,
			&i.TrashName,
			&i.OriginalPath,
			&i.DeletedBy,
			&i.DeletedAt,
			&i.IsDir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
