// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uploads.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (token, user_id, target_path, size, received, stage_id, checksum, created_at, expires_at)
VALUES (?, ?, ?, ?, 0, ?, ?, ?, ?)
RETURNING id, token, user_id, target_path, size, received, checksum, created_at, expires_at, stage_id
`

type CreateUploadParams struct {
	Token      string
	UserID     int64
	TargetPath string
	Size       int64
	StageID    string
	Checksum   sql.NullString
	CreatedAt  int64
	ExpiresAt  int64
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, createUpload,
		arg.Token,
		arg.UserID,
		arg.TargetPath,
		arg.Size,
		arg.StageID,
		arg.Checksum,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.TargetPath,
		&i.Size,
		&i.Received,
		&i.Checksum,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.StageID,
	)
	return i, err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = ?
`

func (q *Queries) DeleteUpload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUpload, id)
	return err
}

const getUpload = `-- name: GetUpload :one
SELECT id, token, user_id, target_path, size, received, checksum, created_at, expires_at, stage_id FROM uploads WHERE token = ? AND expires_at > ?
`

type GetUploadParams struct {
	Token     string
	ExpiresAt int64
}

// Expiry is filtered here so an abandoned session cannot be revived days later
// by a client that kept its token.
func (q *Queries) GetUpload(ctx context.Context, arg GetUploadParams) (Upload, error) {
	row := q.db.QueryRowContext(ctx, getUpload, arg.Token, arg.ExpiresAt)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.TargetPath,
		&i.Size,
		&i.Received,
		&i.Checksum,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.StageID,
	)
	return i, err
}

const listExpiredUploads = `-- name: ListExpiredUploads :many
SELECT id, token, user_id, target_path, size, received, checksum, created_at, expires_at, stage_id FROM uploads WHERE expires_at <= ?
`

func (q *Queries) ListExpiredUploads(ctx context.Context, expiresAt int64) ([]Upload, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredUploads, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.UserID,
			&i.TargetPath,
			&i.Size,
			&i.Received,
			&i.Checksum,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.StageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUploadOffset = `-- name: UpdateUploadOffset :exec
UPDATE uploads SET received = ? WHERE id = ?
`

type UpdateUploadOffsetParams struct {
	Received int64
	ID       int64
}

func (q *Queries) UpdateUploadOffset(ctx context.Context, arg UpdateUploadOffsetParams) error {
	_, err := q.db.ExecContext(ctx, updateUploadOffset, arg.Received, arg.ID)
	return err
}
